[2024-01-04T10:25:27.708+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Cricbuzz_ETL.transfer_to_hdfs manual__2024-01-04T04:55:18.546006+00:00 [queued]>
[2024-01-04T10:25:27.716+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Cricbuzz_ETL.transfer_to_hdfs manual__2024-01-04T04:55:18.546006+00:00 [queued]>
[2024-01-04T10:25:27.716+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-04T10:25:27.729+0530] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transfer_to_hdfs> on 2024-01-04 04:55:18.546006+00:00
[2024-01-04T10:25:27.731+0530] {standard_task_runner.py:57} INFO - Started process 19305 to run task
[2024-01-04T10:25:27.734+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Cricbuzz_ETL', 'transfer_to_hdfs', 'manual__2024-01-04T04:55:18.546006+00:00', '--job-id', '744', '--raw', '--subdir', 'DAGS_FOLDER/Crickbuzz_dag.py', '--cfg-path', '/tmp/tmpsn3ohlch']
[2024-01-04T10:25:27.735+0530] {standard_task_runner.py:85} INFO - Job 744: Subtask transfer_to_hdfs
[2024-01-04T10:25:27.763+0530] {task_command.py:416} INFO - Running <TaskInstance: Cricbuzz_ETL.transfer_to_hdfs manual__2024-01-04T04:55:18.546006+00:00 [running]> on host Iris
[2024-01-04T10:25:27.819+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Cricbuzz_ETL' AIRFLOW_CTX_TASK_ID='transfer_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T04:55:18.546006+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-04T04:55:18.546006+00:00'
[2024-01-04T10:25:27.824+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_hadoop' for task execution.
[2024-01-04T10:25:27.824+0530] {webhdfs.py:81} INFO - Trying to connect to 79be0d725b69/172.22.0.6:8020
[2024-01-04T10:25:27.825+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/rajabala/Desktop/projects/Airflow/dags/Crickbuzz_dag.py", line 168, in load_to_hadoop
    conn.get_conn()
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/apache/hdfs/hooks/webhdfs.py", line 71, in get_conn
    connection = self._find_valid_server()
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/apache/hdfs/hooks/webhdfs.py", line 83, in _find_valid_server
    conn_check = host_socket.connect_ex((namenode, connection.port))
socket.gaierror: [Errno -2] Name or service not known
[2024-01-04T10:25:27.828+0530] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Cricbuzz_ETL, task_id=transfer_to_hdfs, execution_date=20240104T045518, start_date=20240104T045527, end_date=20240104T045527
[2024-01-04T10:25:27.838+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 744 for task transfer_to_hdfs ([Errno -2] Name or service not known; 19305)
[2024-01-04T10:25:27.866+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-04T10:25:27.884+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
