[2024-01-02T17:20:50.616+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Cricbuzz_ETL.Create_balls_table scheduled__2023-12-29T00:00:00+00:00 [queued]>
[2024-01-02T17:20:50.624+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Cricbuzz_ETL.Create_balls_table scheduled__2023-12-29T00:00:00+00:00 [queued]>
[2024-01-02T17:20:50.624+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2024-01-02T17:20:50.639+0530] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): Create_balls_table> on 2023-12-29 00:00:00+00:00
[2024-01-02T17:20:50.641+0530] {standard_task_runner.py:57} INFO - Started process 11828 to run task
[2024-01-02T17:20:50.644+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Cricbuzz_ETL', 'Create_balls_table', 'scheduled__2023-12-29T00:00:00+00:00', '--job-id', '540', '--raw', '--subdir', 'DAGS_FOLDER/Crickbuzz_dag.py', '--cfg-path', '/tmp/tmpejxwoomr']
[2024-01-02T17:20:50.644+0530] {standard_task_runner.py:85} INFO - Job 540: Subtask Create_balls_table
[2024-01-02T17:20:50.674+0530] {task_command.py:416} INFO - Running <TaskInstance: Cricbuzz_ETL.Create_balls_table scheduled__2023-12-29T00:00:00+00:00 [running]> on host Iris
[2024-01-02T17:20:50.722+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Cricbuzz_ETL' AIRFLOW_CTX_TASK_ID='Create_balls_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-29T00:00:00+00:00'
[2024-01-02T17:20:50.722+0530] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS Ball_by_ball_data(
            "match_id" NUMERIC ,
            "ball" TEXT,
            "Commentary Text" TEXT,
            "innings" TEXT,
            "batting_team" TEXT,
            "bowling_team"TEXT,      
            "Batsman" TEXT,
            "Bowler" TEXT,
            "runs" TEXT, 
            "extra" TEXT, 
            "ball_length" TEXT, 
            "ball_line" TEXT,
            "ball_speed" TEXT,
            "shot_name" TEXT, 
            "ball_destination" TEXT, 
            "out_type" TEXT 
            )
[2024-01-02T17:20:50.726+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_db' for task execution.
[2024-01-02T17:20:51.003+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_db' for task execution.
[2024-01-02T17:20:51.004+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-01-02T17:20:51.007+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Cricbuzz_ETL, task_id=Create_balls_table, execution_date=20231229T000000, start_date=20240102T115050, end_date=20240102T115051
[2024-01-02T17:20:51.019+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 540 for task Create_balls_table (connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 11828)
[2024-01-02T17:20:51.056+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-02T17:20:51.076+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-02T17:26:44.858+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Cricbuzz_ETL.Create_balls_table scheduled__2023-12-29T00:00:00+00:00 [queued]>
[2024-01-02T17:26:44.864+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Cricbuzz_ETL.Create_balls_table scheduled__2023-12-29T00:00:00+00:00 [queued]>
[2024-01-02T17:26:44.865+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2024-01-02T17:26:44.877+0530] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): Create_balls_table> on 2023-12-29 00:00:00+00:00
[2024-01-02T17:26:44.879+0530] {standard_task_runner.py:57} INFO - Started process 14767 to run task
[2024-01-02T17:26:44.882+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Cricbuzz_ETL', 'Create_balls_table', 'scheduled__2023-12-29T00:00:00+00:00', '--job-id', '544', '--raw', '--subdir', 'DAGS_FOLDER/Crickbuzz_dag.py', '--cfg-path', '/tmp/tmp9b9fylvg']
[2024-01-02T17:26:44.883+0530] {standard_task_runner.py:85} INFO - Job 544: Subtask Create_balls_table
[2024-01-02T17:26:44.912+0530] {task_command.py:416} INFO - Running <TaskInstance: Cricbuzz_ETL.Create_balls_table scheduled__2023-12-29T00:00:00+00:00 [running]> on host Iris
[2024-01-02T17:26:44.967+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Cricbuzz_ETL' AIRFLOW_CTX_TASK_ID='Create_balls_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-29T00:00:00+00:00'
[2024-01-02T17:26:44.967+0530] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS Ball_by_ball_data(
            "match_id" NUMERIC ,
            "ball" TEXT,
            "Commentary Text" TEXT,
            "innings" TEXT,
            "batting_team" TEXT,
            "bowling_team"TEXT,      
            "Batsman" TEXT,
            "Bowler" TEXT,
            "runs" TEXT, 
            "extra" TEXT, 
            "ball_length" TEXT, 
            "ball_line" TEXT,
            "ball_speed" TEXT,
            "shot_name" TEXT, 
            "ball_destination" TEXT, 
            "out_type" TEXT 
            )
[2024-01-02T17:26:44.971+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_db' for task execution.
[2024-01-02T17:26:45.230+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_db' for task execution.
[2024-01-02T17:26:45.231+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-01-02T17:26:45.234+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Cricbuzz_ETL, task_id=Create_balls_table, execution_date=20231229T000000, start_date=20240102T115644, end_date=20240102T115645
[2024-01-02T17:26:45.247+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 544 for task Create_balls_table (connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 14767)
[2024-01-02T17:26:45.255+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-02T17:26:45.268+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
