[2023-12-09T15:47:04.028+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Cricbuzz_ETL.load manual__2023-12-09T10:16:58.089101+00:00 [queued]>
[2023-12-09T15:47:04.032+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Cricbuzz_ETL.load manual__2023-12-09T10:16:58.089101+00:00 [queued]>
[2023-12-09T15:47:04.032+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-09T15:47:04.042+0530] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-12-09 10:16:58.089101+00:00
[2023-12-09T15:47:04.045+0530] {standard_task_runner.py:57} INFO - Started process 11780 to run task
[2023-12-09T15:47:04.047+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Cricbuzz_ETL', 'load', 'manual__2023-12-09T10:16:58.089101+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/Crickbuzz_dag.py', '--cfg-path', '/tmp/tmpyl6yz21f']
[2023-12-09T15:47:04.048+0530] {standard_task_runner.py:85} INFO - Job 119: Subtask load
[2023-12-09T15:47:04.070+0530] {task_command.py:416} INFO - Running <TaskInstance: Cricbuzz_ETL.load manual__2023-12-09T10:16:58.089101+00:00 [running]> on host Iris
[2023-12-09T15:47:04.110+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Cricbuzz_ETL' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-12-09T10:16:58.089101+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-09T10:16:58.089101+00:00'
[2023-12-09T15:47:04.124+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_db' for task execution.
[2023-12-09T15:47:04.128+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/rajabala/Desktop/projects/Airflow/dags/Cricbuzz_files/Load.py", line 35, in load_to_db
    engine = create_engine(f'postgresql+psycopg2://{connection.login}:{connection.password}@{connection.host}:{connection.port}/{connection.schema}')
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'login'
[2023-12-09T15:47:04.131+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Cricbuzz_ETL, task_id=load, execution_date=20231209T101658, start_date=20231209T101704, end_date=20231209T101704
[2023-12-09T15:47:04.138+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 119 for task load ('psycopg2.extensions.connection' object has no attribute 'login'; 11780)
[2023-12-09T15:47:04.178+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-09T15:47:04.194+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
