[2023-12-09T08:31:04.611+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Cricbuzz_ETL.transform manual__2023-12-09T03:00:39.782164+00:00 [queued]>
[2023-12-09T08:31:04.615+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Cricbuzz_ETL.transform manual__2023-12-09T03:00:39.782164+00:00 [queued]>
[2023-12-09T08:31:04.615+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-09T08:31:04.624+0530] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-12-09 03:00:39.782164+00:00
[2023-12-09T08:31:04.628+0530] {standard_task_runner.py:57} INFO - Started process 33255 to run task
[2023-12-09T08:31:04.630+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Cricbuzz_ETL', 'transform', 'manual__2023-12-09T03:00:39.782164+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/Crickbuzz_dag.py', '--cfg-path', '/tmp/tmpxiztr3yn']
[2023-12-09T08:31:04.631+0530] {standard_task_runner.py:85} INFO - Job 36: Subtask transform
[2023-12-09T08:31:04.651+0530] {task_command.py:416} INFO - Running <TaskInstance: Cricbuzz_ETL.transform manual__2023-12-09T03:00:39.782164+00:00 [running]> on host Iris
[2023-12-09T08:31:04.687+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Cricbuzz_ETL' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-12-09T03:00:39.782164+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-09T03:00:39.782164+00:00'
[2023-12-09T08:31:04.687+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/rajabala/Desktop/projects/Airflow/dags/Cricbuzz_files/Transform.py", line 4, in clean
    df=pd.read_csv(f'{file_name}.csv')
NameError: name 'pd' is not defined
[2023-12-09T08:31:04.690+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Cricbuzz_ETL, task_id=transform, execution_date=20231209T030039, start_date=20231209T030104, end_date=20231209T030104
[2023-12-09T08:31:04.699+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 36 for task transform (name 'pd' is not defined; 33255)
[2023-12-09T08:31:04.722+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-09T08:31:04.734+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
