[2024-01-06T12:53:47.406+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Cricbuzz_ETL.load_to_postgres scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-06T12:53:47.415+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Cricbuzz_ETL.load_to_postgres scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-06T12:53:47.416+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-06T12:53:47.425+0530] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2024-01-05 00:00:00+00:00
[2024-01-06T12:53:47.428+0530] {standard_task_runner.py:57} INFO - Started process 96345 to run task
[2024-01-06T12:53:47.429+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Cricbuzz_ETL', 'load_to_postgres', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '757', '--raw', '--subdir', 'DAGS_FOLDER/Crickbuzz_dag.py', '--cfg-path', '/tmp/tmp9di_5m6p']
[2024-01-06T12:53:47.430+0530] {standard_task_runner.py:85} INFO - Job 757: Subtask load_to_postgres
[2024-01-06T12:53:47.451+0530] {task_command.py:416} INFO - Running <TaskInstance: Cricbuzz_ETL.load_to_postgres scheduled__2024-01-05T00:00:00+00:00 [running]> on host Iris
[2024-01-06T12:53:47.486+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Cricbuzz_ETL' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-06T12:53:47.489+0530] {logging_mixin.py:154} INFO - None
[2024-01-06T12:53:47.489+0530] {logging_mixin.py:154} INFO - <class 'NoneType'>
[2024-01-06T12:53:47.489+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/rajabala/Desktop/projects/Airflow/dags/Cricbuzz_files/Load.py", line 49, in load_multiple_files
    if len(match_url)>1:
TypeError: object of type 'NoneType' has no len()
[2024-01-06T12:53:47.491+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Cricbuzz_ETL, task_id=load_to_postgres, execution_date=20240105T000000, start_date=20240106T072347, end_date=20240106T072347
[2024-01-06T12:53:47.498+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 757 for task load_to_postgres (object of type 'NoneType' has no len(); 96345)
[2024-01-06T12:53:47.521+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-06T12:53:47.538+0530] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
