[2024-01-04T19:12:07.439+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Cricbuzz_ETL.transfer_to_hdfs manual__2024-01-04T04:52:33.503986+00:00 [queued]>
[2024-01-04T19:12:07.446+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Cricbuzz_ETL.transfer_to_hdfs manual__2024-01-04T04:52:33.503986+00:00 [queued]>
[2024-01-04T19:12:07.446+0530] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-01-04T19:12:07.459+0530] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transfer_to_hdfs> on 2024-01-04 04:52:33.503986+00:00
[2024-01-04T19:12:07.462+0530] {standard_task_runner.py:57} INFO - Started process 76680 to run task
[2024-01-04T19:12:07.465+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Cricbuzz_ETL', 'transfer_to_hdfs', 'manual__2024-01-04T04:52:33.503986+00:00', '--job-id', '747', '--raw', '--subdir', 'DAGS_FOLDER/Crickbuzz_dag.py', '--cfg-path', '/tmp/tmplz9bkelu']
[2024-01-04T19:12:07.465+0530] {standard_task_runner.py:85} INFO - Job 747: Subtask transfer_to_hdfs
[2024-01-04T19:12:07.493+0530] {task_command.py:416} INFO - Running <TaskInstance: Cricbuzz_ETL.transfer_to_hdfs manual__2024-01-04T04:52:33.503986+00:00 [running]> on host Iris
[2024-01-04T19:12:07.538+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Cricbuzz_ETL' AIRFLOW_CTX_TASK_ID='transfer_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T04:52:33.503986+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-04T04:52:33.503986+00:00'
[2024-01-04T19:12:07.538+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/rajabala/Desktop/projects/Airflow/dags/Crickbuzz_dag.py", line 170, in load_to_hadoop
    print(hdfs)
NameError: name 'hdfs' is not defined
[2024-01-04T19:12:07.541+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Cricbuzz_ETL, task_id=transfer_to_hdfs, execution_date=20240104T045233, start_date=20240104T134207, end_date=20240104T134207
[2024-01-04T19:12:07.550+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 747 for task transfer_to_hdfs (name 'hdfs' is not defined; 76680)
[2024-01-04T19:12:07.556+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-04T19:12:07.568+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
