[2023-12-09T16:08:35.386+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Cricbuzz_ETL.load manual__2023-12-09T10:38:29.355401+00:00 [queued]>
[2023-12-09T16:08:35.391+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Cricbuzz_ETL.load manual__2023-12-09T10:38:29.355401+00:00 [queued]>
[2023-12-09T16:08:35.391+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-09T16:08:35.401+0530] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-12-09 10:38:29.355401+00:00
[2023-12-09T16:08:35.405+0530] {standard_task_runner.py:57} INFO - Started process 19110 to run task
[2023-12-09T16:08:35.407+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Cricbuzz_ETL', 'load', 'manual__2023-12-09T10:38:29.355401+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/Crickbuzz_dag.py', '--cfg-path', '/tmp/tmpf2hlmqua']
[2023-12-09T16:08:35.408+0530] {standard_task_runner.py:85} INFO - Job 146: Subtask load
[2023-12-09T16:08:35.430+0530] {task_command.py:416} INFO - Running <TaskInstance: Cricbuzz_ETL.load manual__2023-12-09T10:38:29.355401+00:00 [running]> on host Iris
[2023-12-09T16:08:35.477+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Cricbuzz_ETL' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-12-09T10:38:29.355401+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-09T10:38:29.355401+00:00'
[2023-12-09T16:08:35.493+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_db' for task execution.
[2023-12-09T16:08:35.498+0530] {logging_mixin.py:154} INFO - bala
[2023-12-09T16:08:35.498+0530] {logging_mixin.py:154} INFO - 

---------------------------<class 'psycopg2.extensions.connection'> --------------------------------
[2023-12-09T16:08:35.498+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/rajabala/Desktop/projects/Airflow/dags/Cricbuzz_files/Load.py", line 39, in load_to_db
    for i in conn:
TypeError: 'psycopg2.extensions.connection' object is not iterable
[2023-12-09T16:08:35.502+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Cricbuzz_ETL, task_id=load, execution_date=20231209T103829, start_date=20231209T103835, end_date=20231209T103835
[2023-12-09T16:08:35.510+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 146 for task load ('psycopg2.extensions.connection' object is not iterable; 19110)
[2023-12-09T16:08:35.539+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-09T16:08:35.551+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
