[2024-01-02T17:20:45.524+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Cricbuzz_ETL.Create_balls_table scheduled__2023-12-28T00:00:00+00:00 [queued]>
[2024-01-02T17:20:45.532+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Cricbuzz_ETL.Create_balls_table scheduled__2023-12-28T00:00:00+00:00 [queued]>
[2024-01-02T17:20:45.533+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2024-01-02T17:20:45.547+0530] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): Create_balls_table> on 2023-12-28 00:00:00+00:00
[2024-01-02T17:20:45.550+0530] {standard_task_runner.py:57} INFO - Started process 11755 to run task
[2024-01-02T17:20:45.553+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Cricbuzz_ETL', 'Create_balls_table', 'scheduled__2023-12-28T00:00:00+00:00', '--job-id', '537', '--raw', '--subdir', 'DAGS_FOLDER/Crickbuzz_dag.py', '--cfg-path', '/tmp/tmpw2p80ue9']
[2024-01-02T17:20:45.554+0530] {standard_task_runner.py:85} INFO - Job 537: Subtask Create_balls_table
[2024-01-02T17:20:45.584+0530] {task_command.py:416} INFO - Running <TaskInstance: Cricbuzz_ETL.Create_balls_table scheduled__2023-12-28T00:00:00+00:00 [running]> on host Iris
[2024-01-02T17:20:45.633+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Cricbuzz_ETL' AIRFLOW_CTX_TASK_ID='Create_balls_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-28T00:00:00+00:00'
[2024-01-02T17:20:45.633+0530] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS Ball_by_ball_data(
            "match_id" NUMERIC ,
            "ball" TEXT,
            "Commentary Text" TEXT,
            "innings" TEXT,
            "batting_team" TEXT,
            "bowling_team"TEXT,      
            "Batsman" TEXT,
            "Bowler" TEXT,
            "runs" TEXT, 
            "extra" TEXT, 
            "ball_length" TEXT, 
            "ball_line" TEXT,
            "ball_speed" TEXT,
            "shot_name" TEXT, 
            "ball_destination" TEXT, 
            "out_type" TEXT 
            )
[2024-01-02T17:20:45.637+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_db' for task execution.
[2024-01-02T17:20:45.886+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_db' for task execution.
[2024-01-02T17:20:45.887+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-01-02T17:20:45.893+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Cricbuzz_ETL, task_id=Create_balls_table, execution_date=20231228T000000, start_date=20240102T115045, end_date=20240102T115045
[2024-01-02T17:20:45.904+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 537 for task Create_balls_table (connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 11755)
[2024-01-02T17:20:45.926+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-02T17:20:45.945+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-02T17:26:39.818+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Cricbuzz_ETL.Create_balls_table scheduled__2023-12-28T00:00:00+00:00 [queued]>
[2024-01-02T17:26:39.823+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Cricbuzz_ETL.Create_balls_table scheduled__2023-12-28T00:00:00+00:00 [queued]>
[2024-01-02T17:26:39.823+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2024-01-02T17:26:39.836+0530] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): Create_balls_table> on 2023-12-28 00:00:00+00:00
[2024-01-02T17:26:39.838+0530] {standard_task_runner.py:57} INFO - Started process 14696 to run task
[2024-01-02T17:26:39.843+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Cricbuzz_ETL', 'Create_balls_table', 'scheduled__2023-12-28T00:00:00+00:00', '--job-id', '541', '--raw', '--subdir', 'DAGS_FOLDER/Crickbuzz_dag.py', '--cfg-path', '/tmp/tmpya5mixxe']
[2024-01-02T17:26:39.844+0530] {standard_task_runner.py:85} INFO - Job 541: Subtask Create_balls_table
[2024-01-02T17:26:39.879+0530] {task_command.py:416} INFO - Running <TaskInstance: Cricbuzz_ETL.Create_balls_table scheduled__2023-12-28T00:00:00+00:00 [running]> on host Iris
[2024-01-02T17:26:39.929+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Cricbuzz_ETL' AIRFLOW_CTX_TASK_ID='Create_balls_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-28T00:00:00+00:00'
[2024-01-02T17:26:39.930+0530] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS Ball_by_ball_data(
            "match_id" NUMERIC ,
            "ball" TEXT,
            "Commentary Text" TEXT,
            "innings" TEXT,
            "batting_team" TEXT,
            "bowling_team"TEXT,      
            "Batsman" TEXT,
            "Bowler" TEXT,
            "runs" TEXT, 
            "extra" TEXT, 
            "ball_length" TEXT, 
            "ball_line" TEXT,
            "ball_speed" TEXT,
            "shot_name" TEXT, 
            "ball_destination" TEXT, 
            "out_type" TEXT 
            )
[2024-01-02T17:26:39.934+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_db' for task execution.
[2024-01-02T17:26:40.204+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_db' for task execution.
[2024-01-02T17:26:40.205+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-01-02T17:26:40.210+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Cricbuzz_ETL, task_id=Create_balls_table, execution_date=20231228T000000, start_date=20240102T115639, end_date=20240102T115640
[2024-01-02T17:26:40.223+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 541 for task Create_balls_table (connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 14696)
[2024-01-02T17:26:40.254+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-02T17:26:40.277+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
