[2023-12-31T21:06:29.787+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Cricbuzz_ETL2.Extract scheduled__2023-12-28T00:00:00+00:00 [queued]>
[2023-12-31T21:06:29.797+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Cricbuzz_ETL2.Extract scheduled__2023-12-28T00:00:00+00:00 [queued]>
[2023-12-31T21:06:29.797+0530] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-31T21:06:29.813+0530] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-12-28 00:00:00+00:00
[2023-12-31T21:06:29.816+0530] {standard_task_runner.py:57} INFO - Started process 19527 to run task
[2023-12-31T21:06:29.819+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Cricbuzz_ETL2', 'Extract', 'scheduled__2023-12-28T00:00:00+00:00', '--job-id', '437', '--raw', '--subdir', 'DAGS_FOLDER/summa.py', '--cfg-path', '/tmp/tmpp93qxqtl']
[2023-12-31T21:06:29.821+0530] {standard_task_runner.py:85} INFO - Job 437: Subtask Extract
[2023-12-31T21:06:29.856+0530] {task_command.py:416} INFO - Running <TaskInstance: Cricbuzz_ETL2.Extract scheduled__2023-12-28T00:00:00+00:00 [running]> on host Iris
[2023-12-31T21:06:29.913+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Cricbuzz_ETL2' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-12-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-28T00:00:00+00:00'
[2023-12-31T21:06:29.914+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: web_scrap() takes 1 positional argument but 2 were given
[2023-12-31T21:06:29.917+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Cricbuzz_ETL2, task_id=Extract, execution_date=20231228T000000, start_date=20231231T153629, end_date=20231231T153629
[2023-12-31T21:06:29.928+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 437 for task Extract (web_scrap() takes 1 positional argument but 2 were given; 19527)
[2023-12-31T21:06:29.951+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-31T21:06:29.972+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
