[2023-12-31T21:06:11.533+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Cricbuzz_ETL2.Extract manual__2023-12-31T15:35:54.365320+00:00 [queued]>
[2023-12-31T21:06:11.538+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Cricbuzz_ETL2.Extract manual__2023-12-31T15:35:54.365320+00:00 [queued]>
[2023-12-31T21:06:11.538+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-31T21:06:11.553+0530] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-12-31 15:35:54.365320+00:00
[2023-12-31T21:06:11.556+0530] {standard_task_runner.py:57} INFO - Started process 19259 to run task
[2023-12-31T21:06:11.559+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Cricbuzz_ETL2', 'Extract', 'manual__2023-12-31T15:35:54.365320+00:00', '--job-id', '434', '--raw', '--subdir', 'DAGS_FOLDER/summa.py', '--cfg-path', '/tmp/tmpatucingt']
[2023-12-31T21:06:11.560+0530] {standard_task_runner.py:85} INFO - Job 434: Subtask Extract
[2023-12-31T21:06:11.592+0530] {task_command.py:416} INFO - Running <TaskInstance: Cricbuzz_ETL2.Extract manual__2023-12-31T15:35:54.365320+00:00 [running]> on host Iris
[2023-12-31T21:06:11.644+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Cricbuzz_ETL2' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-12-31T15:35:54.365320+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-31T15:35:54.365320+00:00'
[2023-12-31T21:06:11.645+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: web_scrap() takes 1 positional argument but 2 were given
[2023-12-31T21:06:11.649+0530] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Cricbuzz_ETL2, task_id=Extract, execution_date=20231231T153554, start_date=20231231T153611, end_date=20231231T153611
[2023-12-31T21:06:11.659+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 434 for task Extract (web_scrap() takes 1 positional argument but 2 were given; 19259)
[2023-12-31T21:06:11.691+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-31T21:06:11.715+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
